version: "3.8"

services:
  floci:
    image: floci/floci:latest
    container_name: floci-aws
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      AWS_REGION: us-east-1

  terraform:
    image: hashicorp/terraform:1.9.8
    container_name: finops-terraform
    working_dir: /workspace/terraform
    volumes:
      - .:/workspace
    depends_on:
      - floci
    entrypoint: ["tail", "-f", "/dev/null"]
    environment:
      AWS_REGION: us-east-1
      TF_CLI_ARGS: "-no-color"
